services:
  Evrinoma\MenuBundle\Controller\MenuApiController:
    alias: evrinoma.menu.api.controller
    public: true

  evrinoma.menu.api.controller:
    class: Evrinoma\MenuBundle\Controller\MenuApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@evrinoma.menu.facade'
    autowire: true

  evrinoma.menu.facade:
    class: Evrinoma\MenuBundle\Facade\Menu\Facade
    arguments:
      - '@evrinoma.menu.command.manager'
      - '@evrinoma.menu.query.manager'
      - '@evrinoma.menu.provider.dto'
      - '@evrinoma.menu.adaptor'
    autowire: true

  Evrinoma\MenuBundle\Facade\Menu\FacadeInterface:
    alias: evrinoma.menu.facade

  evrinoma.menu.factory:
    class: Evrinoma\MenuBundle\Factory\MenuFactory
    public: true
    arguments:

  evrinoma.menu.orm.repository:
    class: Evrinoma\MenuBundle\Repository\Orm\Menu\MenuRepository
    public: true
    arguments:

  evrinoma.menu.command.manager:
    class: Evrinoma\MenuBundle\Manager\CommandManager
    arguments:
      - '@evrinoma.menu.validator'
      - '@evrinoma.menu.repository'
      - '@evrinoma.menu.factory'
      - '@evrinoma.menu.command.mediator'

  Evrinoma\MenuBundle\Manager\CommandManagerInterface:
    alias: evrinoma.menu.command.manager

  evrinoma.menu.query.manager:
    class: Evrinoma\MenuBundle\Manager\QueryManager
    arguments:
      - '@evrinoma.menu.repository'

  Evrinoma\MenuBundle\Manager\QueryManagerInterface:
    alias: evrinoma.menu.query.manager

  evrinoma.menu.validator:
    class: Evrinoma\MenuBundle\Validator\MenuValidator
    public: true
    arguments:

  Evrinoma\MenuBundle\Validator\MenuValidator:
    alias: evrinoma.menu.validator

  evrinoma.menu.query.orm.mediator:
    class: Evrinoma\MenuBundle\Mediator\Orm\QueryMediator
    public: true
    arguments:

  Evrinoma\MenuBundle\Mediator\Orm\QueryMediator:
    alias: evrinoma.menu.query.orm.mediator

  evrinoma.menu.command.mediator:
    class: Evrinoma\MenuBundle\Mediator\CommandMediator
    public: true
    arguments:
      - '@evrinoma.menu.repository'

  Evrinoma\MenuBundle\Mediator\CommandMediator:
    alias: evrinoma.menu.command.mediator

  Evrinoma\MenuBundle\Mediator\CommandMediatorInterface:
    alias: evrinoma.menu.command.mediator

  evrinoma.menu.pre.validator:
    class: Evrinoma\MenuBundle\PreValidator\DtoPreValidator
    public: true
    arguments:

  Evrinoma\MenuBundle\PreValidator\DtoPreValidator:
    alias: evrinoma.menu.pre.validator

  Evrinoma\MenuBundle\PreValidator\DtoPreValidatorInterface:
    alias: evrinoma.menu.pre.validator

  evrinoma.menu.form.rest.tag:
    class: Evrinoma\MenuBundle\Form\Rest\MenuTagChoiceType
    arguments:
      - '@evrinoma.menu.query.manager'
    tags: { - name: form.type }

  Evrinoma\MenuBundle\Form\Rest\MenuTagChoiceType:
    alias: evrinoma.menu.form.rest.tag
    public: true

  evrinoma.menu.object.registry:
    class: Evrinoma\MenuBundle\Registry\ObjectRegistry
    public: true
    arguments:

  Evrinoma\MenuBundle\Registry\ObjectRegistryInterface:
    alias: evrinoma.menu.object.registry

  Evrinoma\MenuBundle\Menu\PredefinedMenu:
    autowire: true
    tags:
      - { name: evrinoma.menu }

  evrinoma.menu.provider.dto:
    class: Evrinoma\MenuBundle\Provider\DtoProvider
    public: true
    arguments:
      - '@evrinoma.menu.object.registry'

  Evrinoma\MenuBundle\Provider\DtoProviderInterface:
    alias: evrinoma.menu.provider.dto

  evrinoma.menu.command.create:
    class: Evrinoma\MenuBundle\Command\MenuCreateCommand
    arguments:
      - '@evrinoma.menu.bridge.create'
    tags: { - name: console.command }

  Evrinoma\MenuBundle\Command\MenuCreateCommand:
    alias: evrinoma.menu.command.create
    public: true

  evrinoma.menu.bridge.create:
    class: Evrinoma\MenuBundle\Command\Bridge\MenuCreateBridge
    arguments:
      - '@evrinoma.menu.facade'
    autowire: true
